generators:
  _gauss_default: &gauss_default
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 1
    num_datasets: 31
    borders: [-1, 1]
    num_components: 1
    measure_mode: grid
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: false
    seed: 55



  1D-gaussian-1c-32p:
    <<: *gauss_default
    n_points: 32

  1D-gaussian-1c-64p:
    <<: *gauss_default
    n_points: 64

  1D-gaussian-1c-128p:
    <<: *gauss_default
    n_points: 128

  1D-gaussian-1c-256p:
    <<: *gauss_default
    n_points: 256

  1D-gaussian-1c-512p:
    <<: *gauss_default
    n_points: 512

  1D-gaussian-1c-1024p:
    <<: *gauss_default
    n_points: 1024

  1D-gaussian-1c-2048p:
    <<: *gauss_default
    n_points: 2048

