generators:
  _gauss_default: &gauss_default
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 1
    num_datasets: 30
    borders: [-1, 1]
    cost_fn: uot.utils.costs.cost_euclid_squared
    measure_mode: grid
    cell_discretization: vertex-centered
    use_jax: false
    seed: 55





  1D-gaussian-2c-32p:
    <<: *gauss_default
    n_points: 32
    num_components: 2

  1D-gaussian-2c-64p:
    <<: *gauss_default
    n_points: 64
    num_components: 2

  1D-gaussian-2c-128p:
    <<: *gauss_default
    n_points: 128
    num_components: 2

  1D-gaussian-2c-256p:
    <<: *gauss_default
    n_points: 256
    num_components: 2

  1D-gaussian-2c-512p:
    <<: *gauss_default
    n_points: 512
    num_components: 2

  1D-gaussian-2c-1024p:
    <<: *gauss_default
    n_points: 1024
    num_components: 2

  1D-gaussian-2c-2048p:
    <<: *gauss_default
    n_points: 2048
    num_components: 2



  1D-gaussian-4c-32p:
    <<: *gauss_default
    n_points: 32
    num_components: 4

  1D-gaussian-4c-64p:
    <<: *gauss_default
    n_points: 64
    num_components: 4

  1D-gaussian-4c-128p:
    <<: *gauss_default
    n_points: 128
    num_components: 4

  1D-gaussian-4c-256p:
    <<: *gauss_default
    n_points: 256
    num_components: 4

  1D-gaussian-4c-512p:
    <<: *gauss_default
    n_points: 512
    num_components: 4

  1D-gaussian-4c-1024p:
    <<: *gauss_default
    n_points: 1024
    num_components: 4

  1D-gaussian-4c-2048p:
    <<: *gauss_default
    n_points: 2048
    num_components: 4



  1D-gaussian-6c-32p:
    <<: *gauss_default
    n_points: 32
    num_components: 6

  1D-gaussian-6c-64p:
    <<: *gauss_default
    n_points: 64
    num_components: 6

  1D-gaussian-6c-128p:
    <<: *gauss_default
    n_points: 128
    num_components: 6

  1D-gaussian-6c-256p:
    <<: *gauss_default
    n_points: 256
    num_components: 6

  1D-gaussian-6c-512p:
    <<: *gauss_default
    n_points: 512
    num_components: 6

  1D-gaussian-6c-1024p:
    <<: *gauss_default
    n_points: 1024
    num_components: 6

  1D-gaussian-6c-2048p:
    <<: *gauss_default
    n_points: 2048
    num_components: 6


