param-grids:

solvers:
  lp:
    solver: uot.solvers.linear_programming.LinearProgrammingTwoMarginalSolver
    jit: false

experiment:
  name: Linear Programming Test
  function: uot.experiments.measurement.measure_with_gpu_tracker