param-grids:
  gradient:
    - reg: 1
      maxiter: 1000000
      tol: 0.000001
      learning_rate: 0.002
      momentum: 0.9
    - reg: 0.1
      maxiter: 1000000
      tol: 0.000001
      learning_rate: 0.002
      momentum: 0.9
    - reg: 0.01
      maxiter: 1000000
      tol: 0.000001
      learning_rate: 0.002
      momentum: 0.9
    - reg: 0.001
      maxiter: 1000000
      tol: 0.000001
      learning_rate: 0.002
      momentum: 0.9

solvers:
  sgd:
    solver: uot.solvers.gradient_ascent.GradientAscentMultiMarginalSGD
    jit: true
    param-grid: gradient

experiment:
  name: Gradient Ascent Test
  function: uot.experiments.measurement.measure_with_gpu_tracker
