generators:
  _exponential_defaults: &exponential_defaults
    generator: uot.problems.generators.IndependentExponentialGenerator
    dim:       1
    num_datasets: 30
    measure_mode: discrete
    borders:   [-1, 1]
    cost_fn:   uot.utils.costs.cost_euclid_squared
    seed:      55



  1D-exponential-32p:
    <<: *exponential_defaults
    n_points: 32

  1D-exponential-64p:
    <<: *exponential_defaults
    n_points: 64

  1D-exponential-128p:
    <<: *exponential_defaults
    n_points: 128

  1D-exponential-256p:
    <<: *exponential_defaults
    n_points: 256

  1D-exponential-512p:
    <<: *exponential_defaults
    n_points: 512

  1D-exponential-1024p:
    <<: *exponential_defaults
    n_points: 1024

  1D-exponential-2048p:
    <<: *exponential_defaults
    n_points: 2048

