generators:  
  _gen_hyperb_mixture_default: &gen_hyperb_default
    generator: uot.problems.generators.GeneralizedHyperbolicMixtureGenerator
    dim:       1
    num_datasets: 30
    borders:   [-1, 1]
    measure_mode: discrete
    lambda_bounds: [-2.0, 2.0]
    alpha_bounds:  [1.0, 5.0]
    beta_coef:      0.9
    delta_bounds:  [0.05, 0.3]
    cost_fn:   uot.utils.costs.cost_euclid_squared
    seed:      55





  1D-gen-hyperb-mixture-2c-32p:
    <<: *gen_hyperb_default
    n_points:       32
    num_components: 2

  1D-gen-hyperb-mixture-2c-64p:
    <<: *gen_hyperb_default
    n_points:       64
    num_components: 2

  1D-gen-hyperb-mixture-2c-128p:
    <<: *gen_hyperb_default
    n_points:       128
    num_components: 2

  1D-gen-hyperb-mixture-2c-256p:
    <<: *gen_hyperb_default
    n_points:       256
    num_components: 2

  1D-gen-hyperb-mixture-2c-512p:
    <<: *gen_hyperb_default
    n_points:       512
    num_components: 2

  1D-gen-hyperb-mixture-2c-1024p:
    <<: *gen_hyperb_default
    n_points:       1024
    num_components: 2

  1D-gen-hyperb-mixture-2c-2048p:
    <<: *gen_hyperb_default
    n_points:       2048
    num_components: 2



  1D-gen-hyperb-mixture-4c-32p:
    <<: *gen_hyperb_default
    n_points:       32
    num_components: 4

  1D-gen-hyperb-mixture-4c-64p:
    <<: *gen_hyperb_default
    n_points:       64
    num_components: 4

  1D-gen-hyperb-mixture-4c-128p:
    <<: *gen_hyperb_default
    n_points:       128
    num_components: 4

  1D-gen-hyperb-mixture-4c-256p:
    <<: *gen_hyperb_default
    n_points:       256
    num_components: 4

  1D-gen-hyperb-mixture-4c-512p:
    <<: *gen_hyperb_default
    n_points:       512
    num_components: 4

  1D-gen-hyperb-mixture-4c-1024p:
    <<: *gen_hyperb_default
    n_points:       1024
    num_components: 4

  1D-gen-hyperb-mixture-4c-2048p:
    <<: *gen_hyperb_default
    n_points:       2048
    num_components: 4



  1D-gen-hyperb-mixture-6c-32p:
    <<: *gen_hyperb_default
    n_points:       32
    num_components: 6

  1D-gen-hyperb-mixture-6c-64p:
    <<: *gen_hyperb_default
    n_points:       64
    num_components: 6

  1D-gen-hyperb-mixture-6c-128p:
    <<: *gen_hyperb_default
    n_points:       128
    num_components: 6

  1D-gen-hyperb-mixture-6c-256p:
    <<: *gen_hyperb_default
    n_points:       256
    num_components: 6

  1D-gen-hyperb-mixture-6c-512p:
    <<: *gen_hyperb_default
    n_points:       512
    num_components: 6

  1D-gen-hyperb-mixture-6c-1024p:
    <<: *gen_hyperb_default
    n_points:       1024
    num_components: 6

  1D-gen-hyperb-mixture-6c-2048p:
    <<: *gen_hyperb_default
    n_points:       2048
    num_components: 6


