generators:
  _cauchy_defaults: &cauchy_defaults
    generator: uot.problems.generators.IndependentCauchyGenerator
    dim:       2
    num_datasets: 30
    borders:   [0, 1]
    cost_fn:   uot.utils.costs.cost_euclid_squared
    measure_mode: grid
    cell_discretization: cell-centered
    seed:      55



  2D-cauchy-32p:
    <<: *cauchy_defaults
    n_points: 32

  2D-cauchy-64p:
    <<: *cauchy_defaults
    n_points: 64

  2D-cauchy-128p:
    <<: *cauchy_defaults
    n_points: 128

  2D-cauchy-160p:
    <<: *cauchy_defaults
    n_points: 160

  2D-cauchy-192p:
    <<: *cauchy_defaults
    n_points: 192

