generators:
  _cauchy_defaults: &cauchy_defaults
    generator: uot.problems.generators.IndependentCauchyGenerator
    dim:       3
    num_datasets: 30
    borders:   [-1, 1]
    cost_fn:   uot.utils.costs.cost_euclid_squared
    # discrete | grid
    measure_mode: discrete
    seed:      55



  3D-cauchy-16p:
    <<: *cauchy_defaults
    n_points: 16

  3D-cauchy-24p:
    <<: *cauchy_defaults
    n_points: 24

  3D-cauchy-32p:
    <<: *cauchy_defaults
    n_points: 32
