generators:
  _gauss_default: &gauss_default
    generator: uot.problems.generators.GaussianMixtureGenerator
    dim: 3
    num_datasets: 30
    borders: [-1, 1]
    cost_fn: uot.utils.costs.cost_euclid_squared
    use_jax: false
    measure_mode: discrete
    seed: 55





  3D-gaussian-2c-16p:
    <<: *gauss_default
    n_points: 16
    num_components: 2

  3D-gaussian-2c-24p:
    <<: *gauss_default
    n_points: 24
    num_components: 2

  3D-gaussian-2c-32p:
    <<: *gauss_default
    n_points: 32
    num_components: 2



  3D-gaussian-4c-16p:
    <<: *gauss_default
    n_points: 16
    num_components: 4

  3D-gaussian-4c-24p:
    <<: *gauss_default
    n_points: 24
    num_components: 4

  3D-gaussian-4c-32p:
    <<: *gauss_default
    n_points: 32
    num_components: 4



  3D-gaussian-6c-16p:
    <<: *gauss_default
    n_points: 16
    num_components: 6

  3D-gaussian-6c-24p:
    <<: *gauss_default
    n_points: 24
    num_components: 6

  3D-gaussian-6c-32p:
    <<: *gauss_default
    n_points: 32
    num_components: 6


