generators:  
  _gen_hyperb_mixture_default: &gen_hyperb_default
    generator: uot.problems.generators.GeneralizedHyperbolicMixtureGenerator
    dim:       3
    num_datasets: 30
    borders:   [-1, 1]
    lambda_bounds: [-2.0, 2.0]
    alpha_bounds:  [1.0, 5.0]
    beta_coef:      0.9
    delta_bounds:  [0.05, 0.3]
    cost_fn:   uot.utils.costs.cost_euclid_squared
    measure_mode: discrete
    seed:      55





  3D-gen-hyperb-mixture-2c-16p:
    <<: *gen_hyperb_default
    n_points:       16
    num_components: 2

  3D-gen-hyperb-mixture-2c-24p:
    <<: *gen_hyperb_default
    n_points:       24
    num_components: 2

  3D-gen-hyperb-mixture-2c-32p:
    <<: *gen_hyperb_default
    n_points:       32
    num_components: 2



  3D-gen-hyperb-mixture-4c-16p:
    <<: *gen_hyperb_default
    n_points:       16
    num_components: 4

  3D-gen-hyperb-mixture-4c-24p:
    <<: *gen_hyperb_default
    n_points:       24
    num_components: 4

  3D-gen-hyperb-mixture-4c-32p:
    <<: *gen_hyperb_default
    n_points:       32
    num_components: 4



  3D-gen-hyperb-mixture-6c-16p:
    <<: *gen_hyperb_default
    n_points:       16
    num_components: 6

  3D-gen-hyperb-mixture-6c-24p:
    <<: *gen_hyperb_default
    n_points:       24
    num_components: 6

  3D-gen-hyperb-mixture-6c-32p:
    <<: *gen_hyperb_default
    n_points:       32
    num_components: 6


